export const bookList = new Map([
    ['1mo.html', { abbreviation: '1Mo', title: '1.Mose', bookNum: 1, osisId: 'Gen' }],
    ['2mo.html', { abbreviation: '2Mo', title: '2.Mose', bookNum: 2, osisId: 'Exod' }],
    ['3mo.html', { abbreviation: '3Mo', title: '3.Mose', bookNum: 3, osisId: 'Lev' }],
    ['4mo.html', { abbreviation: '4Mo', title: '4.Mose', bookNum: 4, osisId: 'Num' }],
    ['5mo.html', { abbreviation: '5Mo', title: '5.Mose', bookNum: 5, osisId: 'Deut' }],
    ['jos.html', { abbreviation: 'Jos', title: 'Josua', bookNum: 6, osisId: 'Josh' }],
    ['ri.html', { abbreviation: 'Ri', title: 'Richter', bookNum: 7, osisId: 'Judg' }],
    ['rut.html', { abbreviation: 'Rut', title: 'Rut', bookNum: 8, osisId: 'Ruth' }],
    ['1sam.html', { abbreviation: '1Sam', title: '1.Samuel', bookNum: 9, osisId: '1Sam' }],
    ['2sam.html', { abbreviation: '2Sam', title: '2.Samuel', bookNum: 10, osisId: '2Sam' }],
    ['1koe.html', { abbreviation: '1Koe', title: '1.Könige', bookNum: 11, osisId: '1Kgs' }],
    ['2koe.html', { abbreviation: '2Koe', title: '2.Könige', bookNum: 12, osisId: '2Kgs' }],
    ['1chr.html', { abbreviation: '1Chr', title: '1.Chronik', bookNum: 13, osisId: '1Chr' }],
    ['2chr.html', { abbreviation: '2Chr', title: '2.Chronik', bookNum: 14, osisId: '2Chr' }],
    ['esra.html', { abbreviation: 'Esra', title: 'Esra', bookNum: 15, osisId: 'Ezra' }],
    ['neh.html', { abbreviation: 'Neh', title: 'Nehemia', bookNum: 16, osisId: 'Neh' }],
    ['est.html', { abbreviation: 'Est', title: 'Ester', bookNum: 17, osisId: 'Esth' }],
    ['hiob.html', { abbreviation: 'Hiob', title: 'Hiob', bookNum: 18, osisId: 'Job' }],
    ['ps.html', { abbreviation: 'Ps', title: 'Psalmen', bookNum: 19, osisId: 'Ps' }],
    ['spr.html', { abbreviation: 'Spr', title: 'Sprüche', bookNum: 20, osisId: 'Prov' }],
    ['pred.html', { abbreviation: 'Pred', title: 'Prediger', bookNum: 21, osisId: 'Eccl' }],
    ['hl.html', { abbreviation: 'Hl', title: 'Hoheslied', bookNum: 22, osisId: 'Song' }],
    ['jes.html', { abbreviation: 'Jes', title: 'Jesaja', bookNum: 23, osisId: 'Isa' }],
    ['jer.html', { abbreviation: 'Jer', title: 'Jeremia', bookNum: 24, osisId: 'Jer' }],
    ['kla.html', { abbreviation: 'Kla', title: 'Klagelieder', bookNum: 25, osisId: 'Lam' }],
    ['hes.html', { abbreviation: 'Hes', title: 'Hesekiel', bookNum: 26, osisId: 'Ezek' }],
    ['dan.html', { abbreviation: 'Dan', title: 'Daniel', bookNum: 27, osisId: 'Dan' }],
    ['hos.html', { abbreviation: 'Hos', title: 'Hosea', bookNum: 28, osisId: 'Hos' }],
    ['joel.html', { abbreviation: 'Joel', title: 'Joel', bookNum: 29, osisId: 'Joel' }],
    ['amos.html', { abbreviation: 'Amos', title: 'Amos', bookNum: 30, osisId: 'Amos' }],
    ['obadja.html', { abbreviation: 'Obadja', title: 'Obadja', bookNum: 31, osisId: 'Obad' }],
    ['jona.html', { abbreviation: 'Jona', title: 'Jona', bookNum: 32, osisId: 'Jonah' }],
    ['mi.html', { abbreviation: 'Mi', title: 'Micha', bookNum: 33, osisId: 'Mic' }],
    ['nah.html', { abbreviation: 'Nah', title: 'Nahum', bookNum: 34, osisId: 'Nah' }],
    ['hab.html', { abbreviation: 'Hab', title: 'Habakuk', bookNum: 35, osisId: 'Hab' }],
    ['zef.html', { abbreviation: 'Zef', title: 'Zefanja', bookNum: 36, osisId: 'Zeph' }],
    ['hag.html', { abbreviation: 'Hag', title: 'Haggai', bookNum: 37, osisId: 'Hag' }],
    ['sach.html', { abbreviation: 'Sach', title: 'Sacharja', bookNum: 38, osisId: 'Zech' }],
    ['mal.html', { abbreviation: 'Mal', title: 'Maleachi', bookNum: 39, osisId: 'Mal' }],
    ['mt.html', { abbreviation: 'Mt', title: 'Matthäus', bookNum: 40, osisId: 'Matt' }],
    ['mk.html', { abbreviation: 'Mk', title: 'Markus', bookNum: 41, osisId: 'Mark' }],
    ['lk.html', { abbreviation: 'Lk', title: 'Lukas', bookNum: 42, osisId: 'Luke' }],
    ['jo.html', { abbreviation: 'Jo', title: 'Johannes', bookNum: 43, osisId: 'John' }],
    ['apg.html', { abbreviation: 'Apg', title: 'Apostelgeschichte', bookNum: 44, osisId: 'Acts' }],
    ['roe.html', { abbreviation: 'Roe', title: 'Römer', bookNum: 45, osisId: 'Rom' }],
    ['1kor.html', { abbreviation: '1Kor', title: '1.Korinther', bookNum: 46, osisId: '1Cor' }],
    ['2kor.html', { abbreviation: '2Kor', title: '2.Korinther', bookNum: 47, osisId: '2Cor' }],
    ['gal.html', { abbreviation: 'Gal', title: 'Galater', bookNum: 48, osisId: 'Gal' }],
    ['eph.html', { abbreviation: 'Eph', title: 'Epheser', bookNum: 49, osisId: 'Eph' }],
    ['phil.html', { abbreviation: 'Phil', title: 'Philipper', bookNum: 50, osisId: 'Phil' }],
    ['kol.html', { abbreviation: 'Kol', title: 'Kolosser', bookNum: 51, osisId: 'Col' }],
    [
        '1thes.html',
        { abbreviation: '1Thes', title: '1.Thessalonicher', bookNum: 52, osisId: '1Thess' },
    ],
    [
        '2thes.html',
        { abbreviation: '2Thes', title: '2.Thessalonicher', bookNum: 53, osisId: '2Thess' },
    ],
    ['1tim.html', { abbreviation: '1Tim', title: '1.Timotheus', bookNum: 54, osisId: '1Tim' }],
    ['2tim.html', { abbreviation: '2Tim', title: '2.Timotheus', bookNum: 55, osisId: '2Tim' }],
    ['tit.html', { abbreviation: 'Tit', title: 'Titus', bookNum: 56, osisId: 'Titus' }],
    ['phm.html', { abbreviation: 'Phm', title: 'Philemon', bookNum: 57, osisId: 'Phlm' }],
    ['hebr.html', { abbreviation: 'Hebr', title: 'Hebräer', bookNum: 58, osisId: 'Heb' }],
    ['jak.html', { abbreviation: 'Jak', title: 'Jakobus', bookNum: 59, osisId: 'Jas' }],
    ['1pt.html', { abbreviation: '1Pt', title: '1.Petrus', bookNum: 60, osisId: '1Pet' }],
    ['2pt.html', { abbreviation: '2Pt', title: '2.Petrus', bookNum: 61, osisId: '2Pet' }],
    ['1jo.html', { abbreviation: '1Jo', title: '1.Johannes', bookNum: 62, osisId: '1John' }],
    ['2jo.html', { abbreviation: '2Jo', title: '2.Johannes', bookNum: 63, osisId: '2John' }],
    ['3jo.html', { abbreviation: '3Jo', title: '3.Johannes', bookNum: 64, osisId: '3John' }],
    ['jud.html', { abbreviation: 'Jud', title: 'Judas', bookNum: 65, osisId: 'Jude' }],
    ['off.html', { abbreviation: 'Off', title: 'Offenbarung', bookNum: 66, osisId: 'Rev' }],
]);
