export const enBookMetadata = new Map([
    ['Gen', { abbreviation: 'Gen.', title: 'Genesis', number: 1 }],
    ['Exod', { abbreviation: 'Ex.', title: 'Exodus', number: 2 }],
    ['Lev', { abbreviation: 'Lev.', title: 'Leviticus', number: 3 }],
    ['Num', { abbreviation: 'Num.', title: 'Numbers', number: 4 }],
    ['Deut', { abbreviation: 'Deut.', title: 'Deuteronomy', number: 5 }],
    ['Josh', { abbreviation: 'Josh.', title: 'Joshua', number: 6 }],
    ['Judg', { abbreviation: 'Judg.', title: 'Judges', number: 7 }],
    ['Ruth', { abbreviation: 'Ruth', title: 'Ruth', number: 8 }],
    ['1Sam', { abbreviation: '1 Sam.', title: '1 Samuel', number: 9 }],
    ['2Sam', { abbreviation: '2 Sam.', title: '2 Samuel', number: 10 }],
    ['1Kgs', { abbreviation: '1 Kings', title: '1 Kings', number: 11 }],
    ['2Kgs', { abbreviation: '2 Kings', title: '2 Kings', number: 12 }],
    ['1Chr', { abbreviation: '1 Chron.', title: '1 Chronicles', number: 13 }],
    ['2Chr', { abbreviation: '2 Chron.', title: '2 Chronicles', number: 14 }],
    ['Ezra', { abbreviation: 'Ezra', title: 'Ezra', number: 15 }],
    ['Neh', { abbreviation: 'Neh.', title: 'Nehemiah', number: 16 }],
    ['Esth', { abbreviation: 'Est.', title: 'Esther', number: 17 }],
    ['Job', { abbreviation: 'Job', title: 'Job', number: 18 }],
    ['Ps', { abbreviation: 'Ps.', title: 'Psalms', number: 19 }],
    ['Prov', { abbreviation: 'Prov.', title: 'Proverbs', number: 20 }],
    ['Eccl', { abbreviation: 'Eccles.', title: 'Ecclesiastes', number: 21 }],
    ['Song', { abbreviation: 'Song', title: 'Song of Solomon', number: 22 }],
    ['Isa', { abbreviation: 'Isa.', title: 'Isaiah', number: 23 }],
    ['Jer', { abbreviation: 'Jer.', title: 'Jeremiah', number: 24 }],
    ['Lam', { abbreviation: 'Lam.', title: 'Lamentations', number: 25 }],
    ['Ezek', { abbreviation: 'Ezek.', title: 'Ezekiel', number: 26 }],
    ['Dan', { abbreviation: 'Dan.', title: 'Daniel', number: 27 }],
    ['Hos', { abbreviation: 'Hos.', title: 'Hosea', number: 28 }],
    ['Joel', { abbreviation: 'Joel', title: 'Joel', number: 29 }],
    ['Amos', { abbreviation: 'Amos', title: 'Amos', number: 30 }],
    ['Obad', { abbreviation: 'Obad.', title: 'Obadiah', number: 31 }],
    ['Jonah', { abbreviation: 'Jonah', title: 'Jonah', number: 32 }],
    ['Mic', { abbreviation: 'Mic.', title: 'Micah', number: 33 }],
    ['Nah', { abbreviation: 'Nah.', title: 'Nahum', number: 34 }],
    ['Hab', { abbreviation: 'Hab.', title: 'Habakkuk', number: 35 }],
    ['Zeph', { abbreviation: 'Zeph.', title: 'Zephaniah', number: 36 }],
    ['Hag', { abbreviation: 'Hag.', title: 'Haggai', number: 37 }],
    ['Zech', { abbreviation: 'Zech.', title: 'Zechariah', number: 38 }],
    ['Mal', { abbreviation: 'Mal.', title: 'Malachi', number: 39 }],
    ['Matt', { abbreviation: 'Matt.', title: 'Matthew', number: 40 }],
    ['Mark', { abbreviation: 'Mark', title: 'Mark', number: 41 }],
    ['Luke', { abbreviation: 'Luke', title: 'Luke', number: 42 }],
    ['John', { abbreviation: 'John', title: 'John', number: 43 }],
    ['Acts', { abbreviation: 'Acts', title: 'Acts', number: 44 }],
    ['Rom', { abbreviation: 'Rom.', title: 'Romans', number: 45 }],
    ['1Cor', { abbreviation: '1 Cor.', title: '1 Corinthians', number: 46 }],
    ['2Cor', { abbreviation: '2 Cor.', title: '2 Corinthians', number: 47 }],
    ['Gal', { abbreviation: 'Gal.', title: 'Galatians', number: 48 }],
    ['Eph', { abbreviation: 'Eph.', title: 'Ephesians', number: 49 }],
    ['Phil', { abbreviation: 'Phil.', title: 'Philippians', number: 50 }],
    ['Col', { abbreviation: 'Col.', title: 'Colossians', number: 51 }],
    ['1Thess', { abbreviation: '1 Thess.', title: '1 Thessalonians', number: 52 }],
    ['2Thess', { abbreviation: '2 Thess.', title: '2 Thessalonians', number: 53 }],
    ['1Tim', { abbreviation: '1 Tim.', title: '1 Timothy', number: 54 }],
    ['2Tim', { abbreviation: '2 Tim.', title: '2 Timothy', number: 55 }],
    ['Titus', { abbreviation: 'Titus', title: 'Titus', number: 56 }],
    ['Phlm', { abbreviation: 'Philem.', title: 'Philemon', number: 57 }],
    ['Heb', { abbreviation: 'Heb.', title: 'Hebrews', number: 58 }],
    ['Jas', { abbreviation: 'James', title: 'James', number: 59 }],
    ['1Pet', { abbreviation: '1 Pet.', title: '1 Peter', number: 60 }],
    ['2Pet', { abbreviation: '2 Pet.', title: '2 Peter', number: 61 }],
    ['1John', { abbreviation: '1 John', title: '1 John', number: 62 }],
    ['2John', { abbreviation: '2 John', title: '2 John', number: 63 }],
    ['3John', { abbreviation: '3 John', title: '3 John', number: 64 }],
    ['Jude', { abbreviation: 'Jude', title: 'Jude', number: 65 }],
    ['Rev', { abbreviation: 'Rev.', title: 'Revelation', number: 66 }],
]);

export const esBookMetdata = new Map([
    ['Gen', { abbreviation: 'Génesis', title: 'Génesis', number: 1 }],
    ['Exod', { abbreviation: 'Éxodo', title: 'Éxodo', number: 2 }],
    ['Lev', { abbreviation: 'Levítico', title: 'Levítico', number: 3 }],
    ['Num', { abbreviation: 'Números', title: 'Números', number: 4 }],
    ['Deut', { abbreviation: 'Deuteronomio', title: 'Deuteronomio', number: 5 }],
    ['Josh', { abbreviation: 'Josué', title: 'Josué', number: 6 }],
    ['Judg', { abbreviation: 'Jueces', title: 'Jueces', number: 7 }],
    ['Ruth', { abbreviation: 'Rut', title: 'Rut', number: 8 }],
    ['1Sam', { abbreviation: '1 Samuel', title: '1 Samuel', number: 9 }],
    ['2Sam', { abbreviation: '2 Samuel', title: '2 Samuel', number: 10 }],
    ['1Kgs', { abbreviation: '1 Reyes', title: '1 Reyes', number: 11 }],
    ['2Kgs', { abbreviation: '2 Reyes', title: '2 Reyes', number: 12 }],
    ['1Chr', { abbreviation: '1 Crónicas', title: '1 Crónicas', number: 13 }],
    ['2Chr', { abbreviation: '2 Crónicas', title: '2 Crónicas', number: 14 }],
    ['Ezra', { abbreviation: 'Esdras', title: 'Esdras', number: 15 }],
    ['Neh', { abbreviation: 'Nehemías', title: 'Nehemías', number: 16 }],
    ['Esth', { abbreviation: 'Ester', title: 'Ester', number: 17 }],
    ['Job', { abbreviation: 'Job', title: 'Job', number: 18 }],
    ['Ps', { abbreviation: 'Salmos', title: 'Salmos', number: 19 }],
    ['Prov', { abbreviation: 'Proverbios', title: 'Proverbios', number: 20 }],
    ['Eccl', { abbreviation: 'Eclesiastés', title: 'Eclesiastés', number: 21 }],
    ['Song', { abbreviation: 'Cantares', title: 'Cantares', number: 22 }],
    ['Isa', { abbreviation: 'Isaías', title: 'Isaías', number: 23 }],
    ['Jer', { abbreviation: 'Jeremías', title: 'Jeremías', number: 24 }],
    ['Lam', { abbreviation: 'Lamentaciones', title: 'Lamentaciones', number: 25 }],
    ['Ezek', { abbreviation: 'Ezequiel', title: 'Ezequiel', number: 26 }],
    ['Dan', { abbreviation: 'Daniel', title: 'Daniel', number: 27 }],
    ['Hos', { abbreviation: 'Oseas', title: 'Oseas', number: 28 }],
    ['Joel', { abbreviation: 'Joel', title: 'Joel', number: 29 }],
    ['Amos', { abbreviation: 'Amós', title: 'Amós', number: 30 }],
    ['Obad', { abbreviation: 'Abdías', title: 'Abdías', number: 31 }],
    ['Jonah', { abbreviation: 'Jonás', title: 'Jonás', number: 32 }],
    ['Mic', { abbreviation: 'Miqueas', title: 'Miqueas', number: 33 }],
    ['Nah', { abbreviation: 'Nahúm', title: 'Nahúm', number: 34 }],
    ['Hab', { abbreviation: 'Habacuc', title: 'Habacuc', number: 35 }],
    ['Zeph', { abbreviation: 'Sofonías', title: 'Sofonías', number: 36 }],
    ['Hag', { abbreviation: 'Hageo', title: 'Hageo', number: 37 }],
    ['Zech', { abbreviation: 'Zacarías', title: 'Zacarías', number: 38 }],
    ['Mal', { abbreviation: 'Malaquías', title: 'Malaquías', number: 39 }],
    ['Matt', { abbreviation: 'S. Mateo', title: 'S. Mateo', number: 40 }],
    ['Mark', { abbreviation: 'S. Marcos', title: 'S. Marcos', number: 41 }],
    ['Luke', { abbreviation: 'S. Lucas', title: 'S. Lucas', number: 42 }],
    ['John', { abbreviation: 'S. Juan', title: 'S. Juan', number: 43 }],
    ['Acts', { abbreviation: 'Hechos', title: 'Hechos', number: 44 }],
    ['Rom', { abbreviation: 'Romanos', title: 'Romanos', number: 45 }],
    ['1Cor', { abbreviation: '1 Corintios', title: '1 Corintios', number: 46 }],
    ['2Cor', { abbreviation: '2 Corintios', title: '2 Corintios', number: 47 }],
    ['Gal', { abbreviation: 'Gálatas', title: 'Gálatas', number: 48 }],
    ['Eph', { abbreviation: 'Efesios', title: 'Efesios', number: 49 }],
    ['Phil', { abbreviation: 'Filipenses', title: 'Filipenses', number: 50 }],
    ['Col', { abbreviation: 'Colosenses', title: 'Colosenses', number: 51 }],
    ['1Thess', { abbreviation: '1 Tesalonicenses', title: '1 Tesalonicenses', number: 52 }],
    ['2Thess', { abbreviation: '2 Tesalonicenses', title: '2 Tesalonicenses', number: 53 }],
    ['1Tim', { abbreviation: '1 Timoteo', title: '1 Timoteo', number: 54 }],
    ['2Tim', { abbreviation: '2 Timoteo', title: '2 Timoteo', number: 55 }],
    ['Titus', { abbreviation: 'Tito', title: 'Tito', number: 56 }],
    ['Phlm', { abbreviation: 'Filemón', title: 'Filemón', number: 57 }],
    ['Heb', { abbreviation: 'Hebreos', title: 'Hebreos', number: 58 }],
    ['Jas', { abbreviation: 'Santiago', title: 'Santiago', number: 59 }],
    ['1Pet', { abbreviation: '1 Pedro', title: '1 Pedro', number: 60 }],
    ['2Pet', { abbreviation: '2 Pedro', title: '2 Pedro', number: 61 }],
    ['1John', { abbreviation: '1 Juan', title: '1 Juan', number: 62 }],
    ['2John', { abbreviation: '2 Juan', title: '2 Juan', number: 63 }],
    ['3John', { abbreviation: '3 Juan', title: '3 Juan', number: 64 }],
    ['Jude', { abbreviation: 'Judas', title: 'Judas', number: 65 }],
    ['Rev', { abbreviation: 'Apocalipsis', title: 'Apocalipsis', number: 66 }],
]);

export const frBookMetdata = new Map([
    ['Gen', { abbreviation: 'Ge.', title: 'Genèse', number: 1 }],
    ['Exod', { abbreviation: 'Ex.', title: 'Exode', number: 2 }],
    ['Lev', { abbreviation: 'Lé.', title: 'Lévitique', number: 3 }],
    ['Num', { abbreviation: 'No.', title: 'Nombres', number: 4 }],
    ['Deut', { abbreviation: 'De.', title: 'Deutéronome', number: 5 }],
    ['Josh', { abbreviation: 'Jos.', title: 'Josué', number: 6 }],
    ['Judg', { abbreviation: 'Jg.', title: 'Juges', number: 7 }],
    ['Ruth', { abbreviation: 'Ru.', title: 'Ruth', number: 8 }],
    ['1Sam', { abbreviation: '1 S.', title: '1 Samuel', number: 9 }],
    ['2Sam', { abbreviation: '2 S.', title: '2 Samuel', number: 10 }],
    ['1Kgs', { abbreviation: '1 R.', title: '1 Rois', number: 11 }],
    ['2Kgs', { abbreviation: '2 R.', title: '2 Rois', number: 12 }],
    ['1Chr', { abbreviation: '1 Ch.', title: '1 Chroniques', number: 13 }],
    ['2Chr', { abbreviation: '2 Ch.', title: '2 Chroniques', number: 14 }],
    ['Ezra', { abbreviation: 'Esd.', title: 'Esdras', number: 15 }],
    ['Neh', { abbreviation: 'Né.', title: 'Néhémie', number: 16 }],
    ['Esth', { abbreviation: 'Est.', title: 'Esther', number: 17 }],
    ['Job', { abbreviation: 'Job', title: 'Job', number: 18 }],
    ['Ps', { abbreviation: 'Ps.', title: 'Psaume', number: 19 }],
    ['Prov', { abbreviation: 'Pr.', title: 'Proverbes', number: 20 }],
    ['Eccl', { abbreviation: 'Ec.', title: 'Ecclésiaste', number: 21 }],
    ['Song', { abbreviation: 'Ca.', title: 'Cantique des Cantiques', number: 22 }],
    ['Isa', { abbreviation: 'Es.', title: 'Ésaïe', number: 23 }],
    ['Jer', { abbreviation: 'Jé.', title: 'Jérémie', number: 24 }],
    ['Lam', { abbreviation: 'La.', title: 'Lamentations', number: 25 }],
    ['Ezek', { abbreviation: 'Ez.', title: 'Ézéchiel', number: 26 }],
    ['Dan', { abbreviation: 'Da.', title: 'Daniel', number: 27 }],
    ['Hos', { abbreviation: 'Os.', title: 'Osée', number: 28 }],
    ['Joel', { abbreviation: 'Joë.', title: 'Joël', number: 29 }],
    ['Amos', { abbreviation: 'Am.', title: 'Amos', number: 30 }],
    ['Obad', { abbreviation: 'Ab.', title: 'Abdias', number: 31 }],
    ['Jonah', { abbreviation: 'Jon.', title: 'Jonas', number: 32 }],
    ['Mic', { abbreviation: 'Mi.', title: 'Michée', number: 33 }],
    ['Nah', { abbreviation: 'Na.', title: 'Nahum', number: 34 }],
    ['Hab', { abbreviation: 'Ha.', title: 'Habacuc', number: 35 }],
    ['Zeph', { abbreviation: 'So.', title: 'Sophonie', number: 36 }],
    ['Hag', { abbreviation: 'Ag.', title: 'Aggée', number: 37 }],
    ['Zech', { abbreviation: 'Za.', title: 'Zacharie', number: 38 }],
    ['Mal', { abbreviation: 'Mal.', title: 'Malachie', number: 39 }],
    ['Matt', { abbreviation: 'Mt.', title: 'Matthieu', number: 40 }],
    ['Mark', { abbreviation: 'Mc.', title: 'Marc', number: 41 }],
    ['Luke', { abbreviation: 'Lu.', title: 'Luc', number: 42 }],
    ['John', { abbreviation: 'Jn.', title: 'Jean', number: 43 }],
    ['Acts', { abbreviation: 'Ac.', title: 'Actes', number: 44 }],
    ['Rom', { abbreviation: 'Ro.', title: 'Romains', number: 45 }],
    ['1Cor', { abbreviation: '1 Co.', title: '1 Corinthiens', number: 46 }],
    ['2Cor', { abbreviation: '2 Co.', title: '2 Corinthiens', number: 47 }],
    ['Gal', { abbreviation: 'Ga.', title: 'Galates', number: 48 }],
    ['Eph', { abbreviation: 'Ep.', title: 'Éphésiens', number: 49 }],
    ['Phil', { abbreviation: 'Ph.', title: 'Philippiens', number: 50 }],
    ['Col', { abbreviation: 'Col.', title: 'Colossiens', number: 51 }],
    ['1Thess', { abbreviation: '1 Th.', title: '1 Thessaloniciens', number: 52 }],
    ['2Thess', { abbreviation: '2 Th.', title: '2 Thessaloniciens', number: 53 }],
    ['1Tim', { abbreviation: '1 Ti.', title: '1 Timothée', number: 54 }],
    ['2Tim', { abbreviation: '2 Ti.', title: '2 Timothée', number: 55 }],
    ['Titus', { abbreviation: 'Tit.', title: 'Tite', number: 56 }],
    ['Phlm', { abbreviation: 'Phm.', title: 'Philémon', number: 57 }],
    ['Heb', { abbreviation: 'Hé.', title: 'Hébreux', number: 58 }],
    ['Jas', { abbreviation: 'Ja.', title: 'Jacques', number: 59 }],
    ['1Pet', { abbreviation: '1 Pi.', title: '1 Pierre', number: 60 }],
    ['2Pet', { abbreviation: '2 Pi.', title: '2 Pierre', number: 61 }],
    ['1John', { abbreviation: '1 Jn.', title: '1 Jean', number: 62 }],
    ['2John', { abbreviation: '2 Jn.', title: '2 Jean', number: 63 }],
    ['3John', { abbreviation: '3 Jn.', title: '3 Jean', number: 64 }],
    ['Jude', { abbreviation: 'Jud.', title: 'Jude', number: 65 }],
    ['Rev', { abbreviation: 'Ap.', title: 'Apocalypse', number: 66 }],
]);

export const zhsBookMetadata = new Map([
    ['Gen', { abbreviation: '创世记', title: '创世记', number: 1 }],
    ['Exod', { abbreviation: '出埃及记', title: '出埃及记', number: 2 }],
    ['Lev', { abbreviation: '利未记', title: '利未记', number: 3 }],
    ['Num', { abbreviation: '民数记', title: '民数记', number: 4 }],
    ['Deut', { abbreviation: '申命记', title: '申命记', number: 5 }],
    ['Josh', { abbreviation: '约书亚记', title: '约书亚记', number: 6 }],
    ['Judg', { abbreviation: '士师记', title: '士师记', number: 7 }],
    ['Ruth', { abbreviation: '路得记', title: '路得记', number: 8 }],
    ['1Sam', { abbreviation: '撒母耳记上', title: '撒母耳记上', number: 9 }],
    ['2Sam', { abbreviation: '撒母耳记下', title: '撒母耳记下', number: 10 }],
    ['1Kgs', { abbreviation: '列王纪上', title: '列王纪上', number: 11 }],
    ['2Kgs', { abbreviation: '列王纪下', title: '列王纪下', number: 12 }],
    ['1Chr', { abbreviation: '历代志上', title: '历代志上', number: 13 }],
    ['2Chr', { abbreviation: '历代志下', title: '历代志下', number: 14 }],
    ['Ezra', { abbreviation: '以斯拉记', title: '以斯拉记', number: 15 }],
    ['Neh', { abbreviation: '尼希米记', title: '尼希米记', number: 16 }],
    ['Esth', { abbreviation: '以斯帖记', title: '以斯帖记', number: 17 }],
    ['Job', { abbreviation: '约伯记', title: '约伯记', number: 18 }],
    ['Ps', { abbreviation: '诗篇', title: '诗篇', number: 19 }],
    ['Prov', { abbreviation: '箴言', title: '箴言', number: 20 }],
    ['Eccl', { abbreviation: '传道书', title: '传道书', number: 21 }],
    ['Song', { abbreviation: '雅歌', title: '雅歌', number: 22 }],
    ['Isa', { abbreviation: '以赛亚书', title: '以赛亚书', number: 23 }],
    ['Jer', { abbreviation: '耶利米书', title: '耶利米书', number: 24 }],
    ['Lam', { abbreviation: '耶利米哀歌', title: '耶利米哀歌', number: 25 }],
    ['Ezek', { abbreviation: '以西结书', title: '以西结书', number: 26 }],
    ['Dan', { abbreviation: '但以理书', title: '但以理书', number: 27 }],
    ['Hos', { abbreviation: '何西阿书', title: '何西阿书', number: 28 }],
    ['Joel', { abbreviation: '约珥书', title: '约珥书', number: 29 }],
    ['Amos', { abbreviation: '阿摩司书', title: '阿摩司书', number: 30 }],
    ['Obad', { abbreviation: '俄巴底亚书', title: '俄巴底亚书', number: 31 }],
    ['Jonah', { abbreviation: '约拿书', title: '约拿书', number: 32 }],
    ['Mic', { abbreviation: '弥迦书', title: '弥迦书', number: 33 }],
    ['Nah', { abbreviation: '那鸿书', title: '那鸿书', number: 34 }],
    ['Hab', { abbreviation: '哈巴谷书', title: '哈巴谷书', number: 35 }],
    ['Zeph', { abbreviation: '西番雅书', title: '西番雅书', number: 36 }],
    ['Hag', { abbreviation: '哈该书', title: '哈该书', number: 37 }],
    ['Zech', { abbreviation: '撒迦利亚书', title: '撒迦利亚书', number: 38 }],
    ['Mal', { abbreviation: '玛拉基书', title: '玛拉基书', number: 39 }],
    ['Matt', { abbreviation: '马太福音', title: '马太福音', number: 40 }],
    ['Mark', { abbreviation: '马可福音', title: '马可福音', number: 41 }],
    ['Luke', { abbreviation: '路加福音', title: '路加福音', number: 42 }],
    ['John', { abbreviation: '约翰福音', title: '约翰福音', number: 43 }],
    ['Acts', { abbreviation: '使徒行传', title: '使徒行传', number: 44 }],
    ['Rom', { abbreviation: '罗马书', title: '罗马书', number: 45 }],
    ['1Cor', { abbreviation: '哥林多前书', title: '哥林多前书', number: 46 }],
    ['2Cor', { abbreviation: '哥林多后书', title: '哥林多后书', number: 47 }],
    ['Gal', { abbreviation: '加拉太书', title: '加拉太书', number: 48 }],
    ['Eph', { abbreviation: '以弗所书', title: '以弗所书', number: 49 }],
    ['Phil', { abbreviation: '腓立比书', title: '腓立比书', number: 50 }],
    ['Col', { abbreviation: '歌罗西书', title: '歌罗西书', number: 51 }],
    ['1Thess', { abbreviation: '帖撒罗尼迦前书', title: '帖撒罗尼迦前书', number: 52 }],
    ['2Thess', { abbreviation: '帖撒罗尼迦后书', title: '帖撒罗尼迦后书', number: 53 }],
    ['1Tim', { abbreviation: '提摩太前书', title: '提摩太前书', number: 54 }],
    ['2Tim', { abbreviation: '提摩太后书', title: '提摩太后书', number: 55 }],
    ['Titus', { abbreviation: '提多书', title: '提多书', number: 56 }],
    ['Phlm', { abbreviation: '腓利门书', title: '腓利门书', number: 57 }],
    ['Heb', { abbreviation: '希伯来书', title: '希伯来书', number: 58 }],
    ['Jas', { abbreviation: '雅各书', title: '雅各书', number: 59 }],
    ['1Pet', { abbreviation: '彼得前书', title: '彼得前书', number: 60 }],
    ['2Pet', { abbreviation: '彼得后书', title: '彼得后书', number: 61 }],
    ['1John', { abbreviation: '约翰一书', title: '约翰一书', number: 62 }],
    ['2John', { abbreviation: '约翰二书', title: '约翰二书', number: 63 }],
    ['3John', { abbreviation: '约翰三书', title: '约翰三书', number: 64 }],
    ['Jude', { abbreviation: '犹大书', title: '犹大书', number: 65 }],
    ['Rev', { abbreviation: '启示录', title: '启示录', number: 66 }],
]);

export const zhBookMetadata = new Map([
    ['Gen', { abbreviation: '創世紀', title: '創世紀', number: 1 }],
    ['Exod', { abbreviation: '出埃及記', title: '出埃及記', number: 2 }],
    ['Lev', { abbreviation: '利未記', title: '利未記', number: 3 }],
    ['Num', { abbreviation: '民數記', title: '民數記', number: 4 }],
    ['Deut', { abbreviation: '申命記', title: '申命記', number: 5 }],
    ['Josh', { abbreviation: '約書亞記', title: '約書亞記', number: 6 }],
    ['Judg', { abbreviation: '士師記', title: '士師記', number: 7 }],
    ['Ruth', { abbreviation: '路得記', title: '路得記', number: 8 }],
    ['1Sam', { abbreviation: '撒母耳記上', title: '撒母耳記上', number: 9 }],
    ['2Sam', { abbreviation: '撒母耳記下', title: '撒母耳記下', number: 10 }],
    ['1Kgs', { abbreviation: '列王紀上', title: '列王紀上', number: 11 }],
    ['2Kgs', { abbreviation: '列王紀下', title: '列王紀下', number: 12 }],
    ['1Chr', { abbreviation: '歷代志上', title: '歷代志上', number: 13 }],
    ['2Chr', { abbreviation: '歷代志下', title: '歷代志下', number: 14 }],
    ['Ezra', { abbreviation: '以斯拉記', title: '以斯拉記', number: 15 }],
    ['Neh', { abbreviation: '尼希米記', title: '尼希米記', number: 16 }],
    ['Esth', { abbreviation: '以斯帖記', title: '以斯帖記', number: 17 }],
    ['Job', { abbreviation: '約伯記', title: '約伯記', number: 18 }],
    ['Ps', { abbreviation: '詩篇', title: '詩篇', number: 19 }],
    ['Prov', { abbreviation: '箴言', title: '箴言', number: 20 }],
    ['Eccl', { abbreviation: '傳道書', title: '傳道書', number: 21 }],
    ['Song', { abbreviation: '雅歌', title: '雅歌', number: 22 }],
    ['Isa', { abbreviation: '以賽亞書', title: '以賽亞書', number: 23 }],
    ['Jer', { abbreviation: '耶利米書', title: '耶利米書', number: 24 }],
    ['Lam', { abbreviation: '耶利米哀歌', title: '耶利米哀歌', number: 25 }],
    ['Ezek', { abbreviation: '以西結書', title: '以西結書', number: 26 }],
    ['Dan', { abbreviation: '但以理書', title: '但以理書', number: 27 }],
    ['Hos', { abbreviation: '何西阿書', title: '何西阿書', number: 28 }],
    ['Joel', { abbreviation: '約珥書', title: '約珥書', number: 29 }],
    ['Amos', { abbreviation: '阿摩司書', title: '阿摩司書', number: 30 }],
    ['Obad', { abbreviation: '俄巴底亞書', title: '俄巴底亞書', number: 31 }],
    ['Jonah', { abbreviation: '約拿書', title: '約拿書', number: 32 }],
    ['Mic', { abbreviation: '彌迦書', title: '彌迦書', number: 33 }],
    ['Nah', { abbreviation: '那鴻書', title: '那鴻書', number: 34 }],
    ['Hab', { abbreviation: '哈巴谷書', title: '哈巴谷書', number: 35 }],
    ['Zeph', { abbreviation: '西番雅書', title: '西番雅書', number: 36 }],
    ['Hag', { abbreviation: '哈該書', title: '哈該書', number: 37 }],
    ['Zech', { abbreviation: '撒迦利亞書', title: '撒迦利亞書', number: 38 }],
    ['Mal', { abbreviation: '瑪拉基書', title: '瑪拉基書', number: 39 }],
    ['Matt', { abbreviation: '馬太福音', title: '馬太福音', number: 40 }],
    ['Mark', { abbreviation: '馬可福音', title: '馬可福音', number: 41 }],
    ['Luke', { abbreviation: '路加福音', title: '路加福音', number: 42 }],
    ['John', { abbreviation: '約翰福音', title: '約翰福音', number: 43 }],
    ['Acts', { abbreviation: '使徒行傳', title: '使徒行傳', number: 44 }],
    ['Rom', { abbreviation: '羅馬書', title: '羅馬書', number: 45 }],
    ['1Cor', { abbreviation: '歌林多前書', title: '歌林多前書', number: 46 }],
    ['2Cor', { abbreviation: '歌林多後書', title: '歌林多後書', number: 47 }],
    ['Gal', { abbreviation: '加拉太書', title: '加拉太書', number: 48 }],
    ['Eph', { abbreviation: '以弗所書', title: '以弗所書', number: 49 }],
    ['Phil', { abbreviation: '腓利比書', title: '腓利比書', number: 50 }],
    ['Col', { abbreviation: '歌羅西書', title: '歌羅西書', number: 51 }],
    ['1Thess', { abbreviation: '帖撒羅尼迦前書', title: '帖撒羅尼迦前書', number: 52 }],
    ['2Thess', { abbreviation: '帖撒羅尼迦後書', title: '帖撒羅尼迦後書', number: 53 }],
    ['1Tim', { abbreviation: '提摩太前書', title: '提摩太前書', number: 54 }],
    ['2Tim', { abbreviation: '提摩太後書', title: '提摩太後書', number: 55 }],
    ['Titus', { abbreviation: '提多書', title: '提多書', number: 56 }],
    ['Phlm', { abbreviation: '腓利門書', title: '腓利門書', number: 57 }],
    ['Heb', { abbreviation: '希伯來書', title: '希伯來書', number: 58 }],
    ['Jas', { abbreviation: '雅各書', title: '雅各書', number: 59 }],
    ['1Pet', { abbreviation: '彼得前書', title: '彼得前書', number: 60 }],
    ['2Pet', { abbreviation: '彼得後書', title: '彼得後書', number: 61 }],
    ['1John', { abbreviation: '約翰一書', title: '約翰一書', number: 62 }],
    ['2John', { abbreviation: '約翰二書', title: '約翰二書', number: 63 }],
    ['3John', { abbreviation: '約翰三書', title: '約翰三書', number: 64 }],
    ['Jude', { abbreviation: '猶大書', title: '猶大書', number: 65 }],
    ['Rev', { abbreviation: '啟示錄', title: '啟示錄', number: 66 }],
]);