import {MigrationInterface, QueryRunner} from "typeorm";

export class AddPronunciationField1609105701370 implements MigrationInterface {
    name = 'AddPronunciationField1609105701370'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" integer, "sectionId" integer, CONSTRAINT "FK_763d9599de97b88c1adcd12dacb" FOREIGN KEY ("sectionId") REFERENCES "bible_section" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ff9093c7d0193dc69753ff6346" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "bible_cross_reference"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_cross_reference" RENAME TO "bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" integer, CONSTRAINT "FK_66a40d0dd1d4dec456e1241d382" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "bible_note"`);
        await queryRunner.query(`DROP TABLE "bible_note"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_note" RENAME TO "bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_09d57b6b557db9a20107239b77"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_phrase" ("id" integer PRIMARY KEY NOT NULL, "joinToRefId" bigint, "versionId" integer NOT NULL, "versionChapterNum" integer NOT NULL, "versionVerseNum" integer NOT NULL, "versionSubverseNum" integer, "sourceTypeId" integer, "content" text NOT NULL, "linebreak" boolean, "skipSpace" varchar, "modifiers" text, "quoteWho" varchar, "person" varchar, "strongs" text, "joinToVersionRefId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_phrase"("id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId") SELECT "id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId" FROM "bible_phrase"`);
        await queryRunner.query(`DROP TABLE "bible_phrase"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_phrase" RENAME TO "bible_phrase"`);
        await queryRunner.query(`CREATE INDEX "IDX_09d57b6b557db9a20107239b77" ON "bible_phrase" ("versionId") `);
        await queryRunner.query(`CREATE TABLE "temporary_dictionary_entry" ("strong" varchar NOT NULL, "dictionary" varchar NOT NULL, "lemma" varchar, "transliteration" varchar, "gloss" varchar NOT NULL, "content" text, "pronunciation" varchar, PRIMARY KEY ("strong", "dictionary"))`);
        await queryRunner.query(`INSERT INTO "temporary_dictionary_entry"("strong", "dictionary", "lemma", "transliteration", "gloss", "content") SELECT "strong", "dictionary", "lemma", "transliteration", "gloss", "content" FROM "dictionary_entry"`);
        await queryRunner.query(`DROP TABLE "dictionary_entry"`);
        await queryRunner.query(`ALTER TABLE "temporary_dictionary_entry" RENAME TO "dictionary_entry"`);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" integer, "sectionId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "bible_cross_reference"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_cross_reference" RENAME TO "bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" bigint, "sectionId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "bible_cross_reference"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_cross_reference" RENAME TO "bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "bible_note"`);
        await queryRunner.query(`DROP TABLE "bible_note"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_note" RENAME TO "bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" bigint)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "bible_note"`);
        await queryRunner.query(`DROP TABLE "bible_note"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_note" RENAME TO "bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_09d57b6b557db9a20107239b77"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_phrase" ("id" bigint PRIMARY KEY NOT NULL, "joinToRefId" bigint, "versionId" integer NOT NULL, "versionChapterNum" integer NOT NULL, "versionVerseNum" integer NOT NULL, "versionSubverseNum" integer, "sourceTypeId" integer, "content" text NOT NULL, "linebreak" boolean, "skipSpace" varchar, "modifiers" text, "quoteWho" varchar, "person" varchar, "strongs" text, "joinToVersionRefId" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_phrase"("id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId") SELECT "id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId" FROM "bible_phrase"`);
        await queryRunner.query(`DROP TABLE "bible_phrase"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_phrase" RENAME TO "bible_phrase"`);
        await queryRunner.query(`CREATE INDEX "IDX_09d57b6b557db9a20107239b77" ON "bible_phrase" ("versionId") `);
        await queryRunner.query(`DROP INDEX "IDX_9adc280fa0230af76df7a0be0d"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_version" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "uid" varchar NOT NULL, "title" varchar NOT NULL, "description" text, "language" varchar(5) NOT NULL, "copyrightShort" varchar, "copyrightLong" text, "chapterVerseSeparator" varchar NOT NULL, "hasStrongs" boolean, "isPlaintext" boolean, "lastUpdate" datetime NOT NULL DEFAULT (datetime('now')), "dataLocation" varchar NOT NULL, "type" varchar, "abbreviation" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_version"("id", "uid", "title", "description", "language", "copyrightShort", "copyrightLong", "chapterVerseSeparator", "hasStrongs", "isPlaintext", "lastUpdate", "dataLocation", "type", "abbreviation") SELECT "id", "uid", "title", "description", "language", "copyrightShort", "copyrightLong", "chapterVerseSeparator", "hasStrongs", "isPlaintext", "lastUpdate", "dataLocation", "type", "abbreviation" FROM "bible_version"`);
        await queryRunner.query(`DROP TABLE "bible_version"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_version" RENAME TO "bible_version"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9adc280fa0230af76df7a0be0d" ON "bible_version" ("uid") `);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" bigint, "sectionId" integer, CONSTRAINT "FK_7ff9093c7d0193dc69753ff6346" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_763d9599de97b88c1adcd12dacb" FOREIGN KEY ("sectionId") REFERENCES "bible_section" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "bible_cross_reference"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_cross_reference" RENAME TO "bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`CREATE TABLE "temporary_bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" bigint, CONSTRAINT "FK_66a40d0dd1d4dec456e1241d382" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "bible_note"`);
        await queryRunner.query(`DROP TABLE "bible_note"`);
        await queryRunner.query(`ALTER TABLE "temporary_bible_note" RENAME TO "bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`ALTER TABLE "bible_note" RENAME TO "temporary_bible_note"`);
        await queryRunner.query(`CREATE TABLE "bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" bigint)`);
        await queryRunner.query(`INSERT INTO "bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "temporary_bible_note"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`ALTER TABLE "bible_cross_reference" RENAME TO "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE TABLE "bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" bigint, "sectionId" integer)`);
        await queryRunner.query(`INSERT INTO "bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "temporary_bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`DROP INDEX "IDX_9adc280fa0230af76df7a0be0d"`);
        await queryRunner.query(`ALTER TABLE "bible_version" RENAME TO "temporary_bible_version"`);
        await queryRunner.query(`CREATE TABLE "bible_version" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "uid" varchar NOT NULL, "title" varchar NOT NULL, "description" text, "language" varchar(5) NOT NULL, "copyrightShort" varchar, "copyrightLong" text, "chapterVerseSeparator" varchar NOT NULL, "hasStrongs" boolean, "isPlaintext" boolean, "lastUpdate" datetime NOT NULL DEFAULT (datetime('now')), "dataLocation" varchar NOT NULL, "type" text, "abbreviation" text)`);
        await queryRunner.query(`INSERT INTO "bible_version"("id", "uid", "title", "description", "language", "copyrightShort", "copyrightLong", "chapterVerseSeparator", "hasStrongs", "isPlaintext", "lastUpdate", "dataLocation", "type", "abbreviation") SELECT "id", "uid", "title", "description", "language", "copyrightShort", "copyrightLong", "chapterVerseSeparator", "hasStrongs", "isPlaintext", "lastUpdate", "dataLocation", "type", "abbreviation" FROM "temporary_bible_version"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_version"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9adc280fa0230af76df7a0be0d" ON "bible_version" ("uid") `);
        await queryRunner.query(`DROP INDEX "IDX_09d57b6b557db9a20107239b77"`);
        await queryRunner.query(`ALTER TABLE "bible_phrase" RENAME TO "temporary_bible_phrase"`);
        await queryRunner.query(`CREATE TABLE "bible_phrase" ("id" integer PRIMARY KEY NOT NULL, "joinToRefId" bigint, "versionId" integer NOT NULL, "versionChapterNum" integer NOT NULL, "versionVerseNum" integer NOT NULL, "versionSubverseNum" integer, "sourceTypeId" integer, "content" text NOT NULL, "linebreak" boolean, "skipSpace" varchar, "modifiers" text, "quoteWho" varchar, "person" varchar, "strongs" text, "joinToVersionRefId" integer) WITHOUT ROWID`);
        await queryRunner.query(`INSERT INTO "bible_phrase"("id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId") SELECT "id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId" FROM "temporary_bible_phrase"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_phrase"`);
        await queryRunner.query(`CREATE INDEX "IDX_09d57b6b557db9a20107239b77" ON "bible_phrase" ("versionId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`ALTER TABLE "bible_note" RENAME TO "temporary_bible_note"`);
        await queryRunner.query(`CREATE TABLE "bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" integer)`);
        await queryRunner.query(`INSERT INTO "bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "temporary_bible_note"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`ALTER TABLE "bible_note" RENAME TO "temporary_bible_note"`);
        await queryRunner.query(`CREATE TABLE "bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" integer, CONSTRAINT "FK_66a40d0dd1d4dec456e1241d382" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "temporary_bible_note"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`ALTER TABLE "bible_cross_reference" RENAME TO "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE TABLE "bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" integer, "sectionId" integer)`);
        await queryRunner.query(`INSERT INTO "bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "temporary_bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`ALTER TABLE "bible_cross_reference" RENAME TO "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE TABLE "bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" integer, "sectionId" integer, CONSTRAINT "FK_7ff9093c7d0193dc69753ff6346" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "temporary_bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
        await queryRunner.query(`ALTER TABLE "dictionary_entry" RENAME TO "temporary_dictionary_entry"`);
        await queryRunner.query(`CREATE TABLE "dictionary_entry" ("strong" varchar NOT NULL, "dictionary" varchar NOT NULL, "lemma" varchar, "transliteration" varchar, "gloss" varchar NOT NULL, "content" text, PRIMARY KEY ("strong", "dictionary"))`);
        await queryRunner.query(`INSERT INTO "dictionary_entry"("strong", "dictionary", "lemma", "transliteration", "gloss", "content") SELECT "strong", "dictionary", "lemma", "transliteration", "gloss", "content" FROM "temporary_dictionary_entry"`);
        await queryRunner.query(`DROP TABLE "temporary_dictionary_entry"`);
        await queryRunner.query(`DROP INDEX "IDX_09d57b6b557db9a20107239b77"`);
        await queryRunner.query(`ALTER TABLE "bible_phrase" RENAME TO "temporary_bible_phrase"`);
        await queryRunner.query(`CREATE TABLE "bible_phrase" ("id" integer PRIMARY KEY NOT NULL, "joinToRefId" bigint, "versionId" integer NOT NULL, "versionChapterNum" integer NOT NULL, "versionVerseNum" integer NOT NULL, "versionSubverseNum" integer, "sourceTypeId" integer, "content" text NOT NULL, "linebreak" boolean, "skipSpace" varchar, "modifiers" text, "quoteWho" varchar, "person" varchar, "strongs" text, "joinToVersionRefId" integer) WITHOUT ROWID`);
        await queryRunner.query(`INSERT INTO "bible_phrase"("id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId") SELECT "id", "joinToRefId", "versionId", "versionChapterNum", "versionVerseNum", "versionSubverseNum", "sourceTypeId", "content", "linebreak", "skipSpace", "modifiers", "quoteWho", "person", "strongs", "joinToVersionRefId" FROM "temporary_bible_phrase"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_phrase"`);
        await queryRunner.query(`CREATE INDEX "IDX_09d57b6b557db9a20107239b77" ON "bible_phrase" ("versionId") `);
        await queryRunner.query(`DROP INDEX "IDX_66a40d0dd1d4dec456e1241d38"`);
        await queryRunner.query(`ALTER TABLE "bible_note" RENAME TO "temporary_bible_note"`);
        await queryRunner.query(`CREATE TABLE "bible_note" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar, "type" varchar, "content" text NOT NULL, "phraseId" integer, CONSTRAINT "FK_66a40d0dd1d4dec456e1241d382" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bible_note"("id", "key", "type", "content", "phraseId") SELECT "id", "key", "type", "content", "phraseId" FROM "temporary_bible_note"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_note"`);
        await queryRunner.query(`CREATE INDEX "IDX_66a40d0dd1d4dec456e1241d38" ON "bible_note" ("phraseId") `);
        await queryRunner.query(`DROP INDEX "IDX_7ff9093c7d0193dc69753ff634"`);
        await queryRunner.query(`DROP INDEX "IDX_763d9599de97b88c1adcd12dac"`);
        await queryRunner.query(`ALTER TABLE "bible_cross_reference" RENAME TO "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE TABLE "bible_cross_reference" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "normalizedRefId" bigint NOT NULL, "partIndicator" varchar, "normalizedRefIdEnd" bigint, "partIndicatorEnd" varchar, "versionId" integer, "versionChapterNum" integer, "versionVerseNum" integer, "versionChapterEndNum" integer, "versionVerseEndNum" integer, "key" varchar, "phraseId" integer, "sectionId" integer, CONSTRAINT "FK_763d9599de97b88c1adcd12dacb" FOREIGN KEY ("sectionId") REFERENCES "bible_section" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7ff9093c7d0193dc69753ff6346" FOREIGN KEY ("phraseId") REFERENCES "bible_phrase" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "bible_cross_reference"("id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId") SELECT "id", "normalizedRefId", "partIndicator", "normalizedRefIdEnd", "partIndicatorEnd", "versionId", "versionChapterNum", "versionVerseNum", "versionChapterEndNum", "versionVerseEndNum", "key", "phraseId", "sectionId" FROM "temporary_bible_cross_reference"`);
        await queryRunner.query(`DROP TABLE "temporary_bible_cross_reference"`);
        await queryRunner.query(`CREATE INDEX "IDX_7ff9093c7d0193dc69753ff634" ON "bible_cross_reference" ("phraseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_763d9599de97b88c1adcd12dac" ON "bible_cross_reference" ("sectionId") `);
    }

}
