export const bookList = new Map([
    ['1mo.html', { abbvreviation: '1mo', title: '1.Mose', bookNum: 1, osisId: 'Gen' }],
    ['2mo.html', { abbvreviation: '2mo', title: '2.Mose', bookNum: 2, osisId: 'Exod' }],
    ['3mo.html', { abbvreviation: '3mo', title: '3.Mose', bookNum: 3, osisId: 'Lev' }],
    ['4mo.html', { abbvreviation: '4mo', title: '4.Mose', bookNum: 4, osisId: 'Num' }],
    ['5mo.html', { abbvreviation: '5mo', title: '5.Mose', bookNum: 5, osisId: 'Deut' }],
    ['jos.html', { abbvreviation: 'jos', title: 'Josua', bookNum: 6, osisId: 'Josh' }],
    ['ri.html', { abbvreviation: 'ri', title: 'Richter', bookNum: 7, osisId: 'Judg' }],
    ['rut.html', { abbvreviation: 'rut', title: 'Rut', bookNum: 8, osisId: 'Ruth' }],
    ['1sam.html', { abbvreviation: '1sam', title: '1.Samuel', bookNum: 9, osisId: '1Sam' }],
    ['2sam.html', { abbvreviation: '2sam', title: '2.Samuel', bookNum: 10, osisId: '2Sam' }],
    ['1koe.html', { abbvreviation: '1koe', title: '1.K&ouml;nige', bookNum: 11, osisId: '1Kgs' }],
    ['2koe.html', { abbvreviation: '2koe', title: '2.K&ouml;nige', bookNum: 12, osisId: '2Kgs' }],
    ['1chr.html', { abbvreviation: '1chr', title: '1.Chronik', bookNum: 13, osisId: '1Chr' }],
    ['2chr.html', { abbvreviation: '2chr', title: '2.Chronik', bookNum: 14, osisId: '2Chr' }],
    ['esra.html', { abbvreviation: 'esra', title: 'Esra', bookNum: 15, osisId: 'Ezra' }],
    ['neh.html', { abbvreviation: 'neh', title: 'Nehemia', bookNum: 16, osisId: 'Neh' }],
    ['est.html', { abbvreviation: 'est', title: 'Ester', bookNum: 17, osisId: 'Esth' }],
    ['hiob.html', { abbvreviation: 'hiob', title: 'Hiob', bookNum: 18, osisId: 'Job' }],
    ['ps.html', { abbvreviation: 'ps', title: 'Psalmen', bookNum: 19, osisId: 'Ps' }],
    ['spr.html', { abbvreviation: 'spr', title: 'Spr&uuml;che', bookNum: 20, osisId: 'Prov' }],
    ['pred.html', { abbvreviation: 'pred', title: 'Prediger', bookNum: 21, osisId: 'Eccl' }],
    ['hl.html', { abbvreviation: 'hl', title: 'Hoheslied', bookNum: 22, osisId: 'Song' }],
    ['jes.html', { abbvreviation: 'jes', title: 'Jesaja', bookNum: 23, osisId: 'Isa' }],
    ['jer.html', { abbvreviation: 'jer', title: 'Jeremia', bookNum: 24, osisId: 'Jer' }],
    ['kla.html', { abbvreviation: 'kla', title: 'Klagelieder', bookNum: 25, osisId: 'Lam' }],
    ['hes.html', { abbvreviation: 'hes', title: 'Hesekiel', bookNum: 26, osisId: 'Ezek' }],
    ['dan.html', { abbvreviation: 'dan', title: 'Daniel', bookNum: 27, osisId: 'Dan' }],
    ['hos.html', { abbvreviation: 'hos', title: 'Hosea', bookNum: 28, osisId: 'Hos' }],
    ['joel.html', { abbvreviation: 'joel', title: 'Joel', bookNum: 29, osisId: 'Joel' }],
    ['amos.html', { abbvreviation: 'amos', title: 'Amos', bookNum: 30, osisId: 'Amos' }],
    ['obadja.html', { abbvreviation: 'obadja', title: 'Obadja', bookNum: 31, osisId: 'Obad' }],
    ['jona.html', { abbvreviation: 'jona', title: 'Jona', bookNum: 32, osisId: 'Jonah' }],
    ['mi.html', { abbvreviation: 'mi', title: 'Micha', bookNum: 33, osisId: 'Mic' }],
    ['nah.html', { abbvreviation: 'nah', title: 'Nahum', bookNum: 34, osisId: 'Nah' }],
    ['hab.html', { abbvreviation: 'hab', title: 'Habakuk', bookNum: 35, osisId: 'Hab' }],
    ['zef.html', { abbvreviation: 'zef', title: 'Zefanja', bookNum: 36, osisId: 'Zeph' }],
    ['hag.html', { abbvreviation: 'hag', title: 'Haggai', bookNum: 37, osisId: 'Hag' }],
    ['sach.html', { abbvreviation: 'sach', title: 'Sacharja', bookNum: 38, osisId: 'Zech' }],
    ['mal.html', { abbvreviation: 'mal', title: 'Maleachi', bookNum: 39, osisId: 'Mal' }],
    ['mt.html', { abbvreviation: 'mt', title: 'Matth&auml;us', bookNum: 40, osisId: 'Matt' }],
    ['mk.html', { abbvreviation: 'mk', title: 'Markus', bookNum: 41, osisId: 'Mark' }],
    ['lk.html', { abbvreviation: 'lk', title: 'Lukas', bookNum: 42, osisId: 'Luke' }],
    ['jo.html', { abbvreviation: 'jo', title: 'Johannes', bookNum: 43, osisId: 'John' }],
    ['apg.html', { abbvreviation: 'apg', title: 'Apostelgeschichte', bookNum: 44, osisId: 'Acts' }],
    ['roe.html', { abbvreviation: 'roe', title: 'R&ouml;mer', bookNum: 45, osisId: 'Rom' }],
    ['1kor.html', { abbvreviation: '1kor', title: '1.Korinther', bookNum: 46, osisId: '1Cor' }],
    ['2kor.html', { abbvreviation: '2kor', title: '2.Korinther', bookNum: 47, osisId: '2Cor' }],
    ['gal.html', { abbvreviation: 'gal', title: 'Galater', bookNum: 48, osisId: 'Gal' }],
    ['eph.html', { abbvreviation: 'eph', title: 'Epheser', bookNum: 49, osisId: 'Eph' }],
    ['phil.html', { abbvreviation: 'phil', title: 'Philipper', bookNum: 50, osisId: 'Phil' }],
    ['kol.html', { abbvreviation: 'kol', title: 'Kolosser', bookNum: 51, osisId: 'Col' }],
    [
        '1thes.html',
        { abbvreviation: '1thes', title: '1.Thessalonicher', bookNum: 52, osisId: '1Thess' }
    ],
    [
        '2thes.html',
        { abbvreviation: '2thes', title: '2.Thessalonicher', bookNum: 53, osisId: '2Thess' }
    ],
    ['1tim.html', { abbvreviation: '1tim', title: '1.Timotheus', bookNum: 54, osisId: '1Tim' }],
    ['2tim.html', { abbvreviation: '2tim', title: '2.Timotheus', bookNum: 55, osisId: '2Tim' }],
    ['tit.html', { abbvreviation: 'tit', title: 'Titus', bookNum: 56, osisId: 'Titus' }],
    ['phm.html', { abbvreviation: 'phm', title: 'Philemon', bookNum: 57, osisId: 'Phlm' }],
    ['hebr.html', { abbvreviation: 'hebr', title: 'Hebr&auml;er', bookNum: 58, osisId: 'Heb' }],
    ['jak.html', { abbvreviation: 'jak', title: 'Jakobus', bookNum: 59, osisId: 'Jas' }],
    ['1pt.html', { abbvreviation: '1pt', title: '1.Petrus', bookNum: 60, osisId: '1Pet' }],
    ['2pt.html', { abbvreviation: '2pt', title: '2.Petrus', bookNum: 61, osisId: '2Pet' }],
    ['1jo.html', { abbvreviation: '1jo', title: '1.Johannes', bookNum: 62, osisId: '1John' }],
    ['2jo.html', { abbvreviation: '2jo', title: '2.Johannes', bookNum: 63, osisId: '2John' }],
    ['3jo.html', { abbvreviation: '3jo', title: '3.Johannes', bookNum: 64, osisId: '3John' }],
    ['jud.html', { abbvreviation: 'jud', title: 'Judas', bookNum: 65, osisId: 'Jude' }],
    ['off.html', { abbvreviation: 'off', title: 'Offenbarung', bookNum: 66, osisId: 'Rev' }]
]);
